### ISSUE TITLE
Changes for inclusion in MELPA

### ISSUE THREAD

**Issue by flexibeast** [jimm/elisp#1]
i recently created a recipe for `malyon.el` to be included in [MELPA](http://melpa.milkbox.net/). In response to the related pull request, one of the MELPA maintainers noted a number of issues with the `malyon.el` file:

https://github.com/milkypostman/melpa/pull/1793#issuecomment-46746963

Not sure if the `malyon.el` maintainer(s) are willing and/or able to address these issues, but thought i would at least flag them, just in case. :-)

**Comment by jimm** [comment]
@flexibeast, so sorry that I did not see your issue until now. I'm not the maintainer of malyon, I just happen to have a copy of `malyon.el` in my elisp library. I'm closing this issue, since I don't think there is anything I can do to help.
